name: Lint commit messages

on:
  pull_request:

jobs:
  commitizen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v3
      - run: uv sync --group dev

      - run: uv run cz check --rev-range origin/${{ github.base_ref }}..HEAD
